### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by MatthK** [SecureAI-Tools/SecureAI-Tools#17]
While I got it running when accessing it directly, I tried to put the service behind an nginx reverse proxy so I get an https connection and can use a proper domain (https://chat.domain.com/). I can access the login page and the login seemed to work. But then I get an error as it could not reach the post-login-page.

When I try to access https://chat.domain.com/wayne-enterprises it says:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

The console has three errors:

```
Loading failed for the <script> with source “https://chat.domain.com/_next/static/chunks/app/%5BorgSlug%5D/page-2aa903b8231fc651.js”.
```

```
ChunkLoadError: Loading chunk 319 failed.
(error: https://chat.domain.com/_next/static/chunks/app/%5BorgSlug%5D/page-2aa903b8231fc651.js)
```

```
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

My nginx config file is as follows:

```
server {
    server_name chat.domain.com;

    location / {
        proxy_pass http://192.168.7.8:28669/;
        proxy_redirect off;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        client_max_body_size 512M;

    }
    access_log /var/log/nginx/chat.domain.com-access.log;
    error_log /var/log/nginx/chat.domain.com-error.log;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chat.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server
 {
    if ($host = chat.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name chat.domain.com;
    listen 80;
    return 404; # managed by Certbot
}
```

Any idea how I could get that to work with the reverse proxy?

**Comment by JayNakrani** [comment]
> The console has three errors:
> 
> ```
> Loading failed for the <script> with source “https://chat.domain.com/_next/static/chunks/app/%5BorgSlug%5D/page-2aa903b8231fc651.js”.
> ```
> 
> ```
> ChunkLoadError: Loading chunk 319 failed.
> (error: https://chat.domain.com/_next/static/chunks/app/%5BorgSlug%5D/page-2aa903b8231fc651.js)
> ```

Both of these errors have `%5BorgSlug%5D` which decodes to `[orgSlug]`. It's possible that Nginx is somehow not working with special characters in paths like square brackets here. Its should be easy to verify -- can you try accessing another js chunk file w/o any special characters in path from `.next/static/chunks` dir (remember that URL paths have `_next` instead of `.next` in the directory name)? If that loads but any file with `[]` doesn't then it means Nginx isn't mapping/decoding brackets properly.

**Comment by JayNakrani** [comment]
Oh, and you will also need to change `NEXTAUTH_URL` env var to work with reverse proxy

**Comment by MatthK** [comment]
That's a quick reply. 
I adjust the NEXTAUTH_URL in the .env file, but that didn't help. However, after changing that, I can't access it anymore using the IP address.

Where do I find those .js files to try more?
I tried to access `/_next/static/chunks/app/[orgSlug]/page-2aa903b8231fc651.js` but I do get a 404 error for that.

**Comment by JayNakrani** [comment]
> I adjust the NEXTAUTH_URL in the .env file, but that didn't help. However, after changing that, I can't access it anymore using the IP address.

It doesn't load even when loading the exact host:port from NEXTAUTH_URL?

> Where do I find those .js files to try more?

If you are using docker container, then exec into it with `docker exec -it <container-name> /bin/sh`, and then inside that session find files like this: `ls -l .next/static/chunks/`

**Comment by MatthK** [comment]
With the NEXTAUTH_URL set to the domain name, it stops at the post-log-in page with Application error. In the console, it shows the 404 error for the [orgSlug] .js files.

I can access /_next/static/chunks/675-1c121d9c2f010912.js and do get the javascript file.
I an also access /_next/static/chunks/app/layout-e28489e916572e42.js
When I try /_next/static/chunks/app/[orgSlug]/page-2aa903b8231fc651.js then I get a 404 error.

After searching for this problem, I found the solution. The trailing / in the nginx config file at `proxy_pass http://192.168.7.8:28669/;` was the issue. When removing the last / and use `proxy_pass http://192.168.7.8:28669;` then it works.
