### ISSUE TITLE
Any Explanation of this error on Fedora Linux 39 Design 

### ISSUE THREAD

**Issue by mahinthjoe** [SecureAI-Tools/SecureAI-Tools#26]
$ docker compose up -d
[+] Running 0/1
 ⠴ Container secure-ai-tools-inference-1  Starting                         4.5s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

The same Command runs fine on the same machine with Windows 11 & WSL2

**Comment by JayNakrani** [comment]
Oh, that's interesting. Based on the error message it seems to be an issue with `nvidia-container-toolkit` not being able to find shared library.

I found a couple of similar issues:
* https://github.com/NVIDIA/nvidia-container-toolkit/issues/154
* https://github.com/NVIDIA/nvidia-docker/issues/1746#issuecomment-1599302126 -- this comment says Docker Desktop isn't supported by nvidia toolkit, and that this error should not happen with docker-ce. It would be worth trying that out

**Comment by mahinthjoe** [comment]
$ sudo dnf remove docker-desktop
$ sudo docker compose up -d
[+] Running 2/2
 ✔ Container secure-ai-tools-inference-1  Started                                                                                                0.0s 
 ✔ Container secure-ai-tools-web-1        Started    
Browse to http://localhost:28669/log-in
Log in to your account
Invalid credentials!

**Comment by mahinthjoe** [comment]
I tried running it with docker desktop on Fedora Linux hence the error above.
Uninstalled docker desktop and it works fine with docker-ce.
