### ISSUE TITLE
OpenAI not available

### ISSUE THREAD

**Issue by x011** [SecureAI-Tools/SecureAI-Tools#32]
Hi,

First of all, thank you for your dedication to this project.

We noticed that the OpenAI option is missing from the settings in the AI tab. Could you guide us on how to activate it?

![2023-12-13_01h30_30](https://github.com/SecureAI-Tools/SecureAI-Tools/assets/4313821/a24886b6-6eb0-40b8-b661-4e072d033ccd)

**Comment by x011** [comment]
To enable Open AI, we need to edit the .env:

1 - Uncomment `MODEL_PROVIDER_CONFIGS= ....`
2 - Add Open AI apiKey

**Comment by JayNakrani** [comment]
@x011 Yep, you got it right. I will document this better in the README :)
