### ISSUE TITLE
Allow deleting document collections and removing individual documents from a collection

### ISSUE THREAD

**Issue by DaelonSuzuka** [SecureAI-Tools/SecureAI-Tools#47]
Document collections can't be deleted, and documents can't be deleted from collections.

**Comment by JayNakrani** [comment]
Yes, this is missing, and we are looking to add this. Converting this issue into a feature request

**Comment by JayNakrani** [comment]
@DaelonSuzuka @fabriziosalmi We have added the ability to delete document collections in the latest version -- [v0.0.3](https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.3). Please try it out and let me know if you run into any issues.
