### ISSUE TITLE
Feature request: Add form submit button to chat

### ISSUE THREAD

**Issue by hpetersen** [SecureAI-Tools/SecureAI-Tools#52]
When using an iPad to chat i am not able to submit the chat form.
The onScreen iOS keyboard will simply add a new line to the TextField and not submit.

Device: iPad Pro 11” 2020
iOS Version: 17.2

![IMG_0079](https://github.com/SecureAI-Tools/SecureAI-Tools/assets/1536105/fd65f71d-4d64-4158-9528-7f5f680e6661)

**Comment by JayNakrani** [comment]
Oh, nice! I hadn't tested this on iPad (or touch screen devices in general). We will add the submit button 👍

**Comment by JayNakrani** [comment]
@hpetersen We have added submit buttons in the latest version -- [v0.0.3](https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.3). Please try it out and let me know if you run into any issues.

**Comment by hpetersen** [comment]
Works like a charm 👍 Thx @JayNakrani
