### ISSUE TITLE
Feature request: deleting collection(s)

### ISSUE THREAD

**Issue by fabriziosalmi** [SecureAI-Tools/SecureAI-Tools#54]
Helo monsters,
is this something I miss or not?

Thank You for this piece of software, already intensively testing over a 48cpu, 128GB ram Dell at home ;)

**Comment by JayNakrani** [comment]
Yep, we haven't added this yet. We have another similar request at #47

**Comment by JayNakrani** [comment]
@fabriziosalmi We have added the ability to delete document collections in the latest version -- [v0.0.3](https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.3). Please try it out and let me know if you run into any issues.
