### ISSUE TITLE
service "db-migrate-and-seed" didn't complete successfully

### ISSUE THREAD

**Issue by Ignaaa** [SecureAI-Tools/SecureAI-Tools#61]
Hi, I get this error:

service "db-migrate-and-seed" didn't complete successfully

when running   docker compose up -d

I'm on a M2
Thanks!

**Comment by JayNakrani** [comment]
Yes, this has been fixed on main. Can you try using the [docker-compose file on main](https://github.com/SecureAI-Tools/SecureAI-Tools/blob/main/deployment/docker-compose.yml)? It adds health checks so db-migrate-and-seed would only run after db is healthy

**Comment by Ignaaa** [comment]
Thank you! It worked.
