### ISSUE TITLE
typeo in README for MODEL_PROVIDER_CONFIGS

### ISSUE THREAD

**Issue by ArjenR** [SecureAI-Tools/SecureAI-Tools#66]
`MODEL_PROVIDER_CONFIGS='[{"type":"OLLAMA","apiBaseUrl":"http://inference:11434/","apiKey":"","options":{"numGpu":30}}}]'`

should probably read
`MODEL_PROVIDER_CONFIGS='[{"type":"OLLAMA","apiBaseUrl":"http://inference:11434/","apiKey":"","options":[{"numGpu":30}]}]'`

**Comment by JayNakrani** [comment]
Ah! Good catch. The typo is that there is an extra `}` towards the end. I just pushed a fix. Let me know if you find any other issues
