### ISSUE TITLE
Set-AI-model banner shows when using only `mistral` model name

### ISSUE THREAD

**Issue by pythongod** [SecureAI-Tools/SecureAI-Tools#67]
Using latest/instruct model does not work. It will download but repeat the setting up of the dialog.

Using mistral:text (3e3d0b9dcb6a) works and won't show the setup dialog. 

<img width="1059" alt="SCR-20231223-roei" src="https://github.com/SecureAI-Tools/SecureAI-Tools/assets/6061638/88171337-8cfb-4af0-b206-3b6219d54c1c">

Edit: apperently works if i use mistral:7b-instruct for 4d9f4b269c33 
Edit2: Looks like i need to set a tag

**Comment by JayNakrani** [comment]
Oh, I see what is happening. It is pinging Ollama to check if model has been downloaded, and Ollama needs tag name in that API.

Workaround, as you found, is to specify tag. So instead of `mistral` specify `mistral:latest` and it'll work.

**Comment by JayNakrani** [comment]
I just pushed a fix to main, it will be released with the next release. In the meantime, please add `:latest` tag manually -- so instead of `mistral`, use `mistral:latest` and it will work.

**Comment by JayNakrani** [comment]
The fix for this was released in https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.4 . So marking this as resolved. Let me know if you run into any other issues though :)
