### ISSUE TITLE
Logins are force redirected to localhost.

### ISSUE THREAD

**Issue by BloodBlight** [SecureAI-Tools/SecureAI-Tools#7]
When running the container on another host (say 192.168.0.100), after entering a user name and password you are redirected to localhost.

This should be a relative redirect, or allow for an environmental variable to set the target URL.

**Comment by JayNakrani** [comment]
Ah yes. Please change the `NEXTAUTH_URL` env var in `.env` file to point to your desired IP, and then it should work. NextAuth/AuthJS framework uses that for login redirect.

**Comment by BloodBlight** [comment]
Yep, that worked (well, closer now)!

I think that would be a good one to add to the docker-compose template.  Maybe others too?

**Comment by BloodBlight** [comment]
Ignore my last post.

**Comment by JayNakrani** [comment]
Based on the other issue, it looks like you got it working. So closing this issue for now. Please let me know though if I can do anything else on this issue and I'll be happy to reopen it and work on it :)
