### ISSUE TITLE
Can't change app to use non-localhost address

### ISSUE THREAD

**Issue by reederda** [SecureAI-Tools/SecureAI-Tools#93]
The app functions on http://localhost:28669, but when placing this tool behind a reverse proxy it continues to try and redirect to localhost, instead of the new address

Example: Entering login info at https://tools.example.com/log-in and clicking "Log In" redirects to http://localhost:28669/post-log-in after a successful authentication.
Is there a way to change this behavior, perhaps via an environmental variable on the container?

**Comment by JayNakrani** [comment]
To use external domain name, please point the `NEXTAUTH_URL` env var to `https://tools.example.com/` and restart docker containers.

**Comment by reederda** [comment]
My apologies, I missed that line while reading the .env file. Thank you!
